Repository hawks-atlanta/frontend-flutter, pull requests merged in 2023-10, with the labels that each got.

#19 feat: added local biometric authentication
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/com/example/login_mobile/MainActivity.kt
  lib/features/auth/domain/entities/user.dart
  lib/features/auth/infrastructure/datasources/auth_datasource_impl.dart
  lib/features/auth/infrastructure/mappers/user_mapper.dart
  lib/features/auth/presentation/providers/auth_provider.dart
  lib/features/auth/presentation/providers/login_form_provider.dart
  lib/features/auth/presentation/screens/login_screen.dart
  lib/features/shared/infrastructure/inputs/services/key_value_storage_impl.dart
  lib/features/shared/widgets/bottom_sheet.dart
  lib/features/shared/widgets/custom_filled_button.dart
  lib/features/shared/widgets/side_menu.dart
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: feature

#23 chore(0.0.11): release 0.0.11
  CHANGELOG.md
  README.md
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/com/example/login_mobile/MainActivity.kt
  lib/features/auth/domain/entities/user.dart
  lib/features/auth/infrastructure/datasources/auth_datasource_impl.dart
  lib/features/auth/infrastructure/mappers/user_mapper.dart
  lib/features/auth/presentation/providers/auth_provider.dart
  lib/features/auth/presentation/providers/login_form_provider.dart
  lib/features/auth/presentation/screens/login_screen.dart
  lib/features/shared/infrastructure/inputs/services/key_value_storage_impl.dart
  lib/features/shared/widgets/bottom_sheet.dart
  lib/features/shared/widgets/custom_filled_button.dart
  lib/features/shared/widgets/side_menu.dart
  package-lock.json
  package.json
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: feature

#29 feat: register & biometric added (#24)
  android/build.gradle
  lib/config/router/app_router.dart
  lib/features/auth/domain/entities/folder.dart
  lib/features/auth/domain/entities/user.dart
  lib/features/auth/infrastructure/datasources/auth_datasource_impl.dart
  lib/features/auth/infrastructure/errors/auth_errors.dart
  lib/features/auth/presentation/providers/auth_provider.dart
  lib/features/auth/presentation/providers/data_test.dart
  lib/features/auth/presentation/providers/login_form_provider.dart
  lib/features/auth/presentation/providers/register_form_provider.dart
  lib/features/auth/presentation/screens/login_screen.dart
  lib/features/auth/presentation/screens/register_screen.dart
  lib/features/drive/presentation/screens/drive_screen.dart
  lib/features/drive/presentation/screens/storage_screen.dart
  lib/features/shared/infrastructure/inputs/password.dart
  lib/features/shared/infrastructure/inputs/repeat_password.dart
  lib/features/shared/infrastructure/inputs/services/key_value_storage_impl.dart
  lib/features/shared/widgets/bottom_sheet.dart
  lib/features/shared/widgets/custom_text_form_field.dart
  lib/features/shared/widgets/folder.dart
  lib/features/shared/widgets/side_menu.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
  windows/runner/flutter_window.cpp
Labels: feature

#32 chore(release): v0.1.2
  .github/workflows/release.yaml
  CHANGELOG.md
  package-lock.json
  package.json
Labels: cd

#33 fix: user state biometric
  lib/features/auth/presentation/providers/auth_provider.dart
Labels: bug

#34 🐛chore(0.1.4): fixed invalid state in login-screen and biometric state
  CHANGELOG.md
  lib/features/auth/presentation/providers/auth_provider.dart
  package-lock.json
  package.json
Labels: cd, ci

#35 fix: direct connection to server
  .gitignore
  android/app/src/main/AndroidManifest.xml
  lib/config/const/environment.dart
  pubspec.yaml
Labels: bug
